### ISSUE TITLE
Warnings during installation and failing start

### ISSUE THREAD

**Issue by sieppl** [searchkit/searchkit-boilerplate#1]
installation: 
![image](https://cloud.githubusercontent.com/assets/837595/12924854/b5edd98e-cf5b-11e5-8d1c-c405a5e08031.png)

start attempt:

![image](https://cloud.githubusercontent.com/assets/837595/12924866/cd5cbb1c-cf5b-11e5-9dac-ada6e79749e0.png)

Am I missing something?

**Comment by ssetem** [comment]
looks like the npm install phase didn't fully complete, could you try rerunning that

**Comment by ssetem** [comment]
Ok I see the potential issue, you might need to update your node + npm, latest version of npm will flatten transitive deps so express etc are accessible

**Comment by sieppl** [comment]
Updating to node.js 5.6.0 fixed the issue. Thank you!
