### ISSUE TITLE
The demo host seems to be down...

### ISSUE THREAD

**Issue by jvanbrug** [searchkit/searchkit-boilerplate#2]
I cannot get the app to display movie results out-of-the-box, possibly because I cannot get a response from the `host` provided in `app.jsx`: https://d78cfb11f565e845000.qb0x.com/movies

**Comment by ssetem** [comment]
thanks, could you replace the url with this

http://demo.searchkit.co/api/movies

**Comment by jvanbrug** [comment]
Movies! Thanks!
