### ISSUE TITLE
running elasticsearch locally

### ISSUE THREAD

**Issue by hunter-x** [searchkit/searchkit-boilerplate#7]
If I change the link of elasticsearch `const host = "http://demo.searchkit.co/api/movies"
` to `const host = "http://localhost:9200/"
` I get an application without movies. How can I reconstruct the DB locally please !

**Comment by hunter-x** [comment]
solved !
I've installed coffeescript `npm install -g coffee-script`
then run the script here [https://github.com/searchkit/searchkit-demo/tree/master/movie-index](searchkit-demo)
and `const host = "http://localhost:9200/movies"` in SearchPage.jsx

**Comment by ssetem** [comment]
nice one :)
